prog: random_numbers.c selection_sort.c quick_sort.c insertion_sort.c half_sort_numbers.c
	gcc random_numbers.c -o ../bin/random_number.out;
	gcc selection_sort.c -o ../bin/selection_sort.out;
	gcc quick_sort.c -o ../bin/quick_sort.out;
	gcc insertion_sort.c -o ../bin/insertion_sort.out;
	gcc half_sort_numbers.c -o ../bin/half_sorted_numbers.out;